config/routes.rb
OneTripMMS::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'sessions' }
             
  root :to => 'home#index'
  
  resources :places do
    resources :frames do
      collection do
        get 'build_number'
      end
    end
  end
  
  resource :test, :only => [:show] do
    member do
      post 'send_mms'
      post 'receive_sms'
    end
  end
  
  resources :logs, :only => [:index]

  

end

app/models/frame.rb
class Frame < ActiveRecord::Base
  attr_accessible :body, :content, :number, :place_id, :image, :image_cache
  
  before_save :update_content_attribute, :update_image_attribute
  
  belongs_to :place, :counter_cache => true
  
  validates :number, :body, :place_id, :image, :presence => true
  
  validates :number, :numericality => { :only_integer => true, :greater_than_or_equal_to => 1 }
  validates :number, :uniqueness => { :scope => :place_id }
  
  validates :body, :length => { :within => 0..10000 }
  
  mount_uploader :image, ImageUploader
  
  scope :number_asc, order("number ASC")
  
  def mms_content
    "#{self.number}_1.txt,#{content};"
  end
  
  def mms_image
    "#{self.number}_2.#{image_ext},#{image_base64};"
  end
  
  private
  def update_content_attribute
    if body.present? && body_changed?
      self.content = Base64.encode64 self.body.encode("gb2312", { :invalid => :replace, :undef => :replace, :replace => '*' })
    end
  end
  
  def update_image_attribute
    if image.present? && image_changed?
      self.image_base64 = Base64.encode64(open(image.path) { |io| io.read })
      self.image_content_type = MIME::Types.type_for(image.file.original_filename).first.to_s
      self.image_size = image.file.size
      self.image_ext = image.file.extension
    end
  end
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  
  before_filter :find_place
  before_filter :add_place_breadcrumb
  
  def index
    @frames = @place.frames.number_asc
    add_breadcrumb :index
  end

  def new
    add_breadcrumb :new
    @frame = @place.frames.new
  end
  
  def create
    @frame = @place.frames.new params[:frame]
    if @frame.save
      redirect_to place_frames_path(@place), :notice => t('messages.frames.success')
    else
      render :new
    end
    add_breadcrumb :new
  end

  def edit
    @frame = Frame.find params[:id]
    add_breadcrumb :edit
  end
  
  def update
    @frame = Frame.find params[:id]
    if @frame.update_attributes params[:frame]
      redirect_to place_frames_path(@place), :notice => t('messages.frames.success')
    else
      render :edit
    end
    add_breadcrumb :edit
  end
  
  def destroy
    @frame = Frame.find params[:id]
    if @frame.destroy
      redirect_to place_frames_path(@place), :notice => t('messages.frames.success')
    else
      redirect_to place_frames_path(@place), :notice => t('messages.frames.error')
    end
  end
  
  def build_number
    
  end
  
  private
  def find_place
		@place = Place.find params[:place_id]
    raise ActiveRecord::RecordNotFound unless @place
  end
  
  def add_place_breadcrumb
    add_breadcrumb @place.name, place_frames_path(@place)
  end
end

app/views/frames/_base.html.erb
<div class="toolbar">
  <div class="btn-toolbar">
    <div class="btn-group">
      <%= link_to t('links.places.index'), places_path, :class => 'btn btn-success' %>
      <%= link_to_if %w(index).include?(action_name), t('links.frames.new'), new_place_frame_path(@place), :class => 'btn btn-success' %>
      <%= link_to_if %w(new create edit update).include?(action_name), 
                     t('links.frames.index'), place_frames_path(@place), :class => 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/frames/_form.html.erb
<%= simple_form_for([@place, @frame], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.input :number do %>
  <%= f.input_field :number %>
    <%= link_to t('links.frames.build_number'), build_number_place_frames_path(@place), :remote => true, :class => 'btn btn-warning' %>
  <% end %>
  <%= f.input :image, :as => :file %>
  <%= f.input :image_cache, :as => :hidden %>
  <%= f.input :body, :as => :text %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/frames/build_number.js.erb
$("#frame_number").val(<%= @place.frames_count + 1 %>);

app/views/frames/edit.html.erb
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-edit"></i></span>
    <h5><%= t('links.frames.edit') %></h5>
  </div>
  <div class="box-content no-padding">
    <%= render "form" %>
  </div>
</div>

app/views/frames/index.html.erb
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-list"></i></span>
    <h5><%= t('links.frames.index') %></h5>
  </div>
  <div class="box-content">
    <ul class="frames">
      <% @frames.each do |frame| %>
      <li>
        <div class="frame-title">
          <span class="icon"><i class="icon-comment-alt"></i></span>
          <h5><%= t('links.frames.number', :num => frame.number) %></h5>
          <div class="action pull-right">
            <%= link_to raw("<i class=\"icon-edit\"></i>"), edit_place_frame_path(@place, frame), 
                        :title => t('links.frames.edit') %>
            <%= link_to raw("<i class=\"icon-trash\"></i>"),
                        place_frame_path(@place, frame),
                        :method => :delete,
                        :data => { :confirm => t('links.commons.confirm') } %>
          </div>
        </div>
        <div class="frame-content clearfix">
          <div class="frame-image pull-left"><%= image_tag frame.image.url %></div>
          <div class="frame-text"><%= simple_format frame.body %></div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/frames/new.html.erb
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-pencil"></i></span>
    <h5><%= t('links.frames.new') %></h5>
  </div>
  <div class="box-content no-padding">
    <%= render "form" %>
  </div>
</div>