config/routes.rb
OneTripMMS::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'sessions' }
             
  root :to => 'home#index'
  
  resources :places do
    resources :frames do
      collection do
        get 'build_number'
      end
    end
  end
  
  resource :test, :only => [:show] do
    member do
      post 'send_mms'
      post 'receive_sms'
    end
  end
  
  resources :logs, :only => [:index]

  

end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  
  attr_accessible :description, :name, :slug, :return_code, :title
  
  before_save :update_return_code_attribute
  
  has_many :frames, :dependent => :destroy
  
  friendly_id :return_code, :use => :slugged
  
  validates :name, :return_code, :slug, :title, :presence => true
  
  validates :name, :length => { :within => 2..30 }
  validates :name, :uniqueness => true
  
  validates :title, :length => { :within => 2..30 }
  
  validates :return_code, :length => { :within => 2..10 }
  validates :return_code, :format => { :with => /^[A-Za-z]+$/ }
  validates :return_code, :uniqueness => true
  
  validates :slug, :length => { :within => 2..10 }
  validates :slug, :format => { :with => /^[A-Za-z]+$/ }
  validates :slug, :uniqueness => true
  
  validates :description, :length => { :within => 0..100 }
  
  def mms_content
    content = ""
    frames.number_asc.each_with_index do |f, i|
      content << "#{i + 1}_1.txt,#{f.content};"
      content << "#{i + 1}_2.#{f.image_ext},#{f.image_base64};"
    end
    content.chop
  end
  
  def self.receive_sms
    result = Service::SMS.receive_sms
    if result.to_i > 1
      Service::SMS.receive_log result.split("\n").to_s
      result.split("\n").group_by { |item| item.split(",")[3] }.each do |key, value|
        phones = []
        value.map { |v| phones << v.split(",")[2] }
        place = Place.find_by_return_code(key.downcase)
        if !place.blank?
          send_result = Service::MMS.send_mms(:title => place.title, 
                                              :content => place.mms_content, 
                                              :mobile => phones.join(","), 
                                              :stime => "")
          if send_result > 1
            Service::MMS.send_log "phones: #{phones.join(",")}, title: #{place.title}, state: success"
          else
            Service::MMS.send_log "phones: #{phones.join(",")}, title: #{place.title}, state: fail - #{send_result}"
          end
        else
          Service::MMS.send_log "phones: #{phones.join(",")}, key: #{key}, state: #{t('messages.tests.error.f_1')}"
        end
      end
    end
  end
  
  private
  def update_return_code_attribute
    if self.return_code.present?
      self.return_code = self.return_code.downcase
    end
  end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  add_breadcrumb :index, :places_path, :only => [:index]
  
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
    add_breadcrumb :new
  end
  
  def create
    @place = Place.new params[:place]
    if @place.save
      redirect_to places_path, :notice => t('messages.places.success')
    else
      render :new
    end
    add_breadcrumb :new
  end

  def edit
    @place = Place.find params[:id]
    add_breadcrumb :edit
    add_breadcrumb @place.name
  end
  
  def update
    @place = Place.find params[:id]
    add_breadcrumb :edit
    add_breadcrumb @place.name
    if @place.update_attributes params[:place]
      redirect_to places_path, :notice => t('messages.places.success')
    else
      render :edit
    end
  end
  
  def destroy
    @place = Place.find params[:id]
    if @place.destroy
      redirect_to places_path, :notice => t('messages.places.success')
    else
      redirect_to places_path, :notice => t('messages.places.error')
    end
  end
end

app/views/places/_base.html.erb
<div class="toolbar">
  <div class="btn-toolbar">
    <div class="btn-group">
      <%= link_to_if %w(index).include?(action_name), t('links.places.new'), new_place_path, :class => 'btn btn-success' %>
      <%= link_to_if %w(new create edit update).include?(action_name), 
                     t('links.places.index'), places_path, :class => 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/places/_form.html.erb
<%= simple_form_for(@place, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.input :name %>
  <%= f.input :title %>
  <%= f.input :return_code %>
  <%= f.input :description, :as => :text %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/places/edit.html.erb
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-edit"></i></span>
    <h5><%= t('links.places.edit') %></h5>
  </div>
  <div class="box-content no-padding">
    <%= render "form" %>
  </div>
</div>

app/views/places/index.html.erb
<%- model_class = Place -%>
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-th"></i></span>
    <h5><%= t('links.places.index') %></h5>
  </div>
  <div class="box-content">
    <table class="table table-bordered table-striped with-check">
      <thead>
        <tr>
          <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:return_code) %></th>
          <th><%= model_class.human_attribute_name(:description) %></th>
          <th class="action"><%= t('links.commons.action') %></th>
        </tr>
      </thead>
      </tbody>
        <% @places.each do |place| %>
          <tr>
            <td><%= check_box_tag "place_ids[]", place.id, false, :id => "place_#{place.id}" %></td>
            <td><%= link_to place.name, place_frames_path(place) %></td>
            <td><%= place.return_code %></td>
            <td><%= place.description %></td>
            <td class="action">
              <%= link_to raw("<i class=\"icon-eye-open\"></i>"), place_frames_path(place), 
                          :title => t('links.places.show') %>
              <%= link_to raw("<i class=\"icon-edit\"></i>"), edit_place_path(place), 
                          :title => t('links.places.edit') %>
              <%= link_to raw("<i class=\"icon-trash\"></i>"),
                          place_path(place),
                          :method => :delete,
                          :data => { :confirm => t('links.commons.confirm') } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/places/new.html.erb
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-pencil"></i></span>
    <h5><%= t('links.places.new') %></h5>
  </div>
  <div class="box-content no-padding">
    <%= render "form" %>
  </div>
</div>