config/routes.rb
OneTripMMS::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'sessions' }
             
  root :to => 'home#index'
  
  resources :places do
    resources :frames do
      collection do
        get 'build_number'
      end
    end
  end
  
  resource :test, :only => [:show] do
    member do
      post 'send_mms'
      post 'receive_sms'
    end
  end
  
  resources :logs, :only => [:index]

  

end

app/views/layouts/_login.html.erb
<div class="container">
  <div class="content">
    <div class="row">
      <div id="main" class="span4 offset4">
        <div class="well white-bg">
          <%= bootstrap_flash %>
          <div class="well-inner">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : Setting.app_name %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body id="<%= "#{controller_name}-#{action_name}" %>">
    <% if %w(sessions).include?(controller_name) %>
      <%= render "layouts/login" %>
    <% else %>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><%= Setting.app_name %></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li<%= raw ' class="active"' if %w(home).include?(controller_name) %>>
                <%= link_to t("navs.home.index"), root_path %>
              </li>
              <li<%= raw ' class="active"' if %w(places frames).include?(controller_name) %>>
                <%= link_to t("navs.places.index"), places_path %>
              </li>
              <li<%= raw ' class="active"' if %w(tests).include?(controller_name) %>>
                <%= link_to t("navs.tests.show"), test_path %>
              </li>
              <li<%= raw ' class="active"' if %w(logs).include?(controller_name) %>>
                <%= link_to t("navs.logs.index"), logs_path %>
              </li>
            </ul>

            <ul class="nav pull-right">
                <% if user_signed_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="icon-user-md"></i> <%= current_user.email %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="divider"></li>
                      <li><%= link_to(t("helpers.links.logout"), destroy_user_session_path, :method => :delete) %></li>
                    </ul>
                  </li>
                <% end -%>
              </ul>
          </div>
        </div>
      </div>
    </div>


    <div class="container">
        <div class="row">
          <div class="span12"><%= render_breadcrumbs %></div>
          <div class="span12"><%= bootstrap_flash %></div>
          <%= render "layouts/sidebars/#{content_for?(:sidebar) ? 'two_column' : 'full_column' }" %>
        </div>

      <footer>
        <p><%= Setting.company %> &copy; Company 2012</p>
      </footer>

    
    </div>
    <% end %>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>